### ISSUE TITLE
Unable to resize GUI

### ISSUE THREAD

**Issue by matt-sharp** [rafaelpadilla/review_object_detection_metrics#8]
When I launch the GUI I'm unable to resize it to fit my screen resolution.  I only have the capability to minimize or maximise the window.  What this means is I'm unable to see the lower section of the window containing the detail needed for metrics.
Please can this issue be fixed somehow? (without having to change the screen resolution settings on my laptop)

**Comment by rafaelpadilla** [comment]
@matt-sharp 

A quick solution was to make the window shorter, so you can use it with a smaller resolution monitor.

Please, check if that helped.

**Comment by matt-sharp** [comment]
> @matt-sharp
> 
> A quick solution was to make the window shorter, so you can use it with a smaller resolution monitor.
> 
> Please, check if that helped.

@rafaelpadilla I've tried to shorten the window but that doesn't work.  My screen resolution is 1366 x 768 which is the maximum for my laptop.

![image](https://user-images.githubusercontent.com/13571774/107928494-4b94df00-6f70-11eb-9431-53ddf4085baa.png)

**Comment by rafaelpadilla** [comment]
Hi @matt-sharp ,

I would need more time to figure out how to make the interface with a scroll bar.

But for now, I adapted it, so it is completely visible in your resolution. As you can see in the image below, I divided the `Fround Truth` and `detection` sections into tabs to fit it in your monitor.

![image](https://user-images.githubusercontent.com/31217453/108106286-8419e300-706c-11eb-9815-6560762fec74.png)

It is not the final solution, but by now it will work.

Please, update your code with the new version. Then, replace line 10 of the [src/ui/run_ui.py] (https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/src/ui/run_ui.py#L10) file, which reads 
`from src.ui.main_ui import Ui_Dialog as Main_UI` to `from src.ui.main_ui_tabs import Ui_Dialog as Main_UI`

Best regards,
Rafael

**Comment by matt-sharp** [comment]
@rafaelpadilla Thanks for your speedy response.  I've updated the code and have managed to launch the GUI successfully so that it now fits my screen.

**Comment by tylertroy** [comment]
I would also comment that I was using Ubuntu Screen magnification to 200% in Settings > Display because I use a 4K display and the dialogs are ridiculously small. By reverting to 100% the program is usable. I made the above change recommended by @matt-sharp and the tabs are indeed nicer but did not solve my problem. Once reverted to 100% both modes work fine.
